services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: foobar
      POSTGRES_DB: nrkast

  adminer:
    image: adminer:latest
    ports:
      - "9999:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DEFAULT_USERNAME: postgres
      ADMINER_DEFAULT_PASSWORD: foobar
      ADMINER_DEFAULT_DRIVER: pgsql
      ADMINER_DEFAULT_DB: ""
    configs:
      - source: adminer-index.php
        target: /var/www/html/index.php

configs:
  adminer-index.php:
    content: |
      <?php
        if(!count($$_GET)) {
          $$_POST['auth'] = [
            'server' => $$_ENV['ADMINER_DEFAULT_SERVER'],
            'username' => $$_ENV['ADMINER_DEFAULT_USERNAME'],
            'password' => $$_ENV['ADMINER_DEFAULT_PASSWORD'],
            'driver' => $$_ENV['ADMINER_DEFAULT_DRIVER'],
            'db'    => $$_ENV['ADMINER_DEFAULT_DB'],
          ];
        }
        include './adminer.php';
      ?>
