services:
  - type: web
    name: nrkast
    env: docker
    plan: free
    region: frankfurt
    branch: main
    healthCheckPath: /healthz
    envVars:
      - key: PORT
        value: 8080
      - key: DB_CONNECTION
        fromDatabase:
          name: nrkast-db
          property: connectionString

databases:
  - name: nrkast-db
    region: frankfurt
    plan: free
